# Generated by Django 5.2.5 on 2025-08-22 09:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='document category')),
                ('code', models.CharField(max_length=50, verbose_name='document category code')),
            ],
            options={
                'verbose_name': 'document category',
                'verbose_name_plural': 'document categories',
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='document type')),
                ('code', models.CharField(max_length=50, verbose_name='document type code')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.documentcategory', verbose_name='document category')),
            ],
            options={
                'verbose_name': 'document type',
                'verbose_name_plural': 'document types',
            },
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('file_name', models.CharField(max_length=50, verbose_name='file name')),
                ('file', models.FileField(upload_to='documents/', verbose_name='file')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.documenttype', verbose_name='document type')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
            },
        ),
    ]
