# Generated by Django 5.2.5 on 2025-08-26 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='is_issuable',
            field=models.BooleanField(default=False, verbose_name='issuable'),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_requested', models.DateField(auto_now_add=True, verbose_name='date requested')),
                ('date_issued', models.DateField(null=True, verbose_name='date issued')),
                ('document_type', models.ForeignKey(limit_choices_to={'is_issuable': True}, on_delete=django.db.models.deletion.CASCADE, to='document.documenttype', verbose_name='document type')),
            ],
            options={
                'verbose_name': 'request',
                'verbose_name_plural': 'requests',
            },
        ),
        migrations.CreateModel(
            name='RequestRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('document_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='document.documentcategory', verbose_name='document category')),
                ('document_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='document.documenttype', verbose_name='document type')),
                ('requested_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='document.documenttype', verbose_name='requested document')),
            ],
            options={
                'verbose_name': 'requirement',
                'verbose_name_plural': 'requirements',
            },
        ),
    ]
