# Generated by Django 5.2.5 on 2025-08-26 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_documenttype_is_issuable_request_requestrequirement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='requestrequirement',
            name='document_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.documentcategory', verbose_name='document category'),
        ),
        migrations.AlterField(
            model_name='requestrequirement',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.documenttype', verbose_name='document type'),
        ),
        migrations.AlterField(
            model_name='requestrequirement',
            name='requested_document',
            field=models.ForeignKey(limit_choices_to={'is_issuable': True}, on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='document.documenttype', verbose_name='requested document'),
        ),
    ]
